const express = require("express")
const cors = require("cors")
require("dotenv").config()
const app = express()
app.use(cors())
app.use(express.json())

const desafiosRoutes = require("./routes/desafios")
app.use("/desafios",desafiosRoutes)
app.listen(3000, () => console.log("Servidor rodando na porta 3000"))